### PR TITLE
Implement GetRoomUsers

### PR DESCRIPTION
**Pull request by bertique**
Based on
https://github.com/gitterHQ/docs/blob/master/03.Rooms-resource.md

### CODE REVIEW

**Comment by Odonno** [comment]
@bertique That's a good idea !

I put some remarks on your changes.

Although, there is a `q` parameters you can use to execute search of user. Why did you ignore this parameter ?

About git commit message, could you follow the angular convention ? You have examples here : https://github.com/Odonno/Modern-Gitter#commit-convention

Thank you for your contribution.

**Comment by bertique** [comment]
Thanks for the feedback @Odonno 

I saw `q` wasn't implemented for the /rooms query so I didn't add it for consistency. No other reason. I will add it. And will update the commit messages.

Thanks!

**Comment by Odonno** [comment]
I did not see a `q` param when wrote this library. Maybe the docs has been updated.

I'll make updates when I can.

**Comment by bertique** [comment]
yeah that's what I figured. I might just do another pull request for that after this one :)

**Comment by Odonno** [comment]
That's perfect !

I think you made a mistake something in your git : there is still your first commit and you have a commit named `Merge remote-tracking branch 'origin/master'`. Can you make a little `git rebase -i` ?

**Comment by bertique** [comment]
Great, I think i fixed it.

**Pull request merged**
