### PR TITLE
fix(webhook): add Accept header and parse response

### LINKED ISSUE #7: System.Exception was thrown on webhook
Any ideas on why I am getting this:

image

The message is successfully posted to the Webhook, but I get an exception when trying to get the Result back.

Any ideas?

### PR DESCRIPTION
**Pull request by gep13**
fixes #7

### CODE REVIEW

**Comment by gep13** [comment]
@Odonno ok, this seems to work, at least in the testing that I have done.  Let me know what you think about the implementation.

**Comment by Odonno** [comment]
@gep13 So, adding the Accept header make it work ?

I think you've done too much code, I'll refactor something, you'll tell me what you think.

**Comment by gep13** [comment]
Yes, that was the main thing that was required, and then the parsing on the result, as the response wasn't simply "ok"

**Comment by Odonno** [comment]
I've done integration tests for that. It works great, I'll make the commit.

**Comment by gep13** [comment]
Would you like me to rebase this PR against your recent changes on the master branch, or how are you planning on continuing?

**Comment by Odonno** [comment]
No need of rebase now.

**Comment by gep13** [comment]
ok. Let me know if there is anything that you would like me to do.

**Comment by Odonno** [comment]
@gep13 Oh god ! You need to let me push on your fork repository. I am a collaborator on Modern Gitter, not on your new fork. :)

**Comment by gep13** [comment]
no, you should be, I added you a few minutes ago when I saw you were going to be adding some commits.

**Comment by gep13** [comment]
image

**Comment by Odonno** [comment]
Weird, I have an error...

```
src refspec AddRequiredHeader does not match any.
failed to push some refs to 'https://github.com/gep13/gitter-api-pcl.git'
```

**Comment by gep13** [comment]
that is very strange :-(

**Comment by Odonno** [comment]
Ok, I've done the merge. I thought it'll push commits here but now...

Here is the link to the commti I've made : https://github.com/Odonno/gitter-api-pcl/commit/b527242469f52c52aaa85705cea059e276f7a6b0

**Pull request merged**
